/* LeafLog — vegetable crop guides (organic + kitchen fert). N. Hemisphere defaults; adjust for zone. */
window.LEAFLOG_VEGETABLES = [
  {
    id: "tomato",
    name: "Tomato",
    image: "https://images.unsplash.com/photo-1546470427-e262649996c8?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Start seeds indoors 6–8 weeks before your last frost. Transplant outdoors when nights stay above ~10°C and soil is warm (~15°C+)." },
      { h: "Germination", t: "Needs warmth: ideally 21–27°C. Sow ~6 mm deep in fine seed mix; keep moist. A humidity dome helps until sprouts appear." },
      { h: "Potting mix", t: "Seeds: light sterile mix (coco + perlite/vermiculite). Transplants: compost-based mix with extra perlite/pumice for drainage." },
      { h: "Seedlings", t: "Bright light 14–16 h/day; pot up when roots fill cells. First true leaves: optional splash of very weak compost tea. Harden off ~7 days before planting out." },
      { h: "Vegetative growth", t: "Stake or cage indeterminates; mulch soil to steady moisture. Deep, less-frequent water beats constant dribbles." },
      { h: "Organic & kitchen fertilizer", t: "Growth: top-dress compost monthly in pots; diluted nettle/compost tea every 2 weeks. When flowers form, shift toward banana peel tea (diluted) and comfrey tea; reduce heavy nitrogen. Eggshell tea (very dilute) only as gentle calcium support—watering consistency matters more for blossom end rot." },
      { h: "Flowering & fruit", t: "Shake plants lightly in greenhouses for pollination. Keep even soil moisture through fruit set. Remove lower leaves slowly for airflow if crowded." },
      { h: "Harvest", t: "Pick at color break or full ripeness; cut with a short stem. Light compost tea can continue between flushes." },
    ],
  },
  {
    id: "pepper",
    name: "Bell pepper & chili",
    image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Start 8–10 weeks before last frost (peppers are slower than tomatoes). Transplant when weather is settled and warm." },
      { h: "Germination", t: "Warm mat helps: 24–29°C. Seeds can be slow (1–3 weeks). Keep seed mix moist, not soggy." },
      { h: "Potting mix", t: "Same as tomatoes: fine seed mix; later a rich compost + drainage blend in larger pots." },
      { h: "Seedlings", t: "Strong light prevents leggy plants. Pot up before they become root-bound. Harden off gradually—peppers dislike cold wind." },
      { h: "Vegetative growth", t: "Full sun; consistent water. Containers dry faster—check daily in heat." },
      { h: "Organic & kitchen fertilizer", t: "After several true leaves: very dilute compost tea. Growth phase: worm castings top-dress + occasional nettle tea. Once flowering: emphasize potassium with diluted banana peel tea; go easy on fresh manure or strong nitrogen." },
      { h: "Flowering & fruit", t: "Avoid drought swings during fruit set. Hot caps or shade cloth can reduce sun scald on fruits in extreme heat." },
      { h: "Harvest", t: "Cut peppers with snips; green or ripe depending on variety. Picking encourages more fruit on many types." },
    ],
  },
  {
    id: "cucumber",
    name: "Cucumber",
    image: "https://images.unsplash.com/photo-1604977042368-43a783bcc620?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Direct-sow after frost when soil is 18°C+, or start indoors 3–4 weeks before transplant (handle roots gently)." },
      { h: "Germination", t: "Warm soil is key. Sow 2–3 seeds per hole; thin to strongest. Keep consistently moist until emergence." },
      { h: "Potting mix", t: "For starts: standard seed mix. In ground: fertile, well-drained soil with compost worked in." },
      { h: "Seedlings", t: "Do not disturb roots much when transplanting. Protect from cold nights." },
      { h: "Vegetative growth", t: "Trellis bush/vining types as labeled; improves airflow and straight fruit. Steady water prevents bitter fruit." },
      { h: "Organic & kitchen fertilizer", t: "Compost side-dress at planting. Liquid: weak compost tea weekly during rapid vine growth. At flowering: add diluted banana peel tea for potassium. Unsalted veg cooking water (cooled) as occasional mild boost." },
      { h: "Flowering & fruit", t: "Pick often so plants keep producing. Watch for cucumber beetles—row cover early, then remove for pollination." },
      { h: "Harvest", t: "Harvest young for best texture; use scissors to avoid tearing vines." },
    ],
  },
  {
    id: "lettuce",
    name: "Lettuce",
    image: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Cool weather crop: spring and fall. In hot summers, choose heat-tolerant varieties or shade cloth. Succession sow every 2 weeks." },
      { h: "Germination", t: "Cooler germination than tomatoes (~15–20°C). Surface-sow or very shallow; light can help some varieties—check packet." },
      { h: "Potting mix", t: "Fine, moisture-retentive seed mix; good drainage to prevent damping off." },
      { h: "Seedlings", t: "Thin early for airspace; eat thinnings. Transplant or direct-sow in rows/containers." },
      { h: "Vegetative growth", t: "Consistent moisture; afternoon shade slows bolting in heat. Mulch keeps soil cool." },
      { h: "Organic & kitchen fertilizer", t: "Light feeder: compost at planting is often enough. If pale: one or two very dilute compost teas—avoid strong nitrogen that makes sappy, disease-prone leaves." },
      { h: "Flowering (bolting)", t: "Long days + heat trigger bolt; leaves turn bitter. Pull and re-sow for fall crop." },
      { h: "Harvest", t: "Cut-and-come-again outer leaves or whole head at maturity. Morning harvest is crispest." },
    ],
  },
  {
    id: "spinach",
    name: "Spinach",
    image: "https://images.unsplash.com/photo-1576045057993-3f9a98478480?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Early spring and late summer/fall. Hot weather causes fast bolting." },
      { h: "Germination", t: "Prefers cool soil. Pre-chilling seed in fridge 1 week can improve germination in warm springs." },
      { h: "Potting mix", t: "Rich in organic matter; good drainage. Containers need frequent water." },
      { h: "Seedlings", t: "Thin to spacing on packet; overcrowding holds moisture and invites disease." },
      { h: "Vegetative growth", t: "Partial shade acceptable in warm spells. Keep soil evenly moist." },
      { h: "Organic & kitchen fertilizer", t: "Compost or worm castings at sowing. If needed: dilute compost tea sparingly—spinach is sensitive to over-fertilizing." },
      { h: "Flowering", t: "Bolt = harvest window ending; re-sow for next cool period." },
      { h: "Harvest", t: "Pick outer leaves or whole rosette before plants elongate and flower." },
    ],
  },
  {
    id: "kale",
    name: "Kale",
    image: "https://images.unsplash.com/photo-1524170239751-97c1f2727049?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Spring transplants or direct-sow; fall kale is often sweetest after light frost." },
      { h: "Germination", t: "Cool–moderate temperatures. Sow 1 cm deep in rows or cells." },
      { h: "Potting mix", t: "Standard seed mix; field planting benefits from compost incorporation." },
      { h: "Seedlings", t: "Space for air movement to reduce mildew. Harden off transplants." },
      { h: "Vegetative growth", t: "Full sun to part shade. Water deeply; mulch." },
      { h: "Organic & kitchen fertilizer", t: "Side-dress compost mid-season. Nettle or compost tea (dilute) if leaves look pale. Avoid excess nitrogen late if aphids explode." },
      { h: "No true “fruit”", t: "Grown for leaves; remove flower stalks if they appear to prolong harvest." },
      { h: "Harvest", t: "Pick bottom leaves upward; plant keeps producing. Flavor improves after frost in many climates." },
    ],
  },
  {
    id: "broccoli",
    name: "Broccoli",
    image: "https://images.unsplash.com/photo-1589621316382-0084550047e7?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Spring: start indoors 6–8 weeks before last frost, or buy transplants. Fall crop: time so heads mature in cool weather." },
      { h: "Germination", t: "Moderate warmth; consistent moisture. Thin or transplant to final spacing early." },
      { h: "Potting mix", t: "Rich seed mix; transplants need steady fertility from compost." },
      { h: "Seedlings", t: "Don’t let them stall in small pots—transplant on time to avoid stunted heads." },
      { h: "Vegetative growth", t: "Heavy nitrogen early for leaves; steady water. Mulch roots." },
      { h: "Organic & kitchen fertilizer", t: "Compost + worm castings at planting. Growth: compost tea or nettle tea diluted. As head forms, avoid huge nitrogen spikes; potassium from banana tea in very dilute form can support quality." },
      { h: "Head formation", t: "Watch for yellow petals—harvest before flowers open fully. Heat speeds loose heads." },
      { h: "Harvest", t: "Cut main head; many varieties produce side shoots for weeks." },
    ],
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    image: "https://images.unsplash.com/photo-1610344499336-30cd0d5b442d?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Similar to broccoli—often easier from transplants. Needs consistent cool period for quality curds." },
      { h: "Germination", t: "Same as broccoli; keep seedlings moving—check days-to-maturity on packet." },
      { h: "Potting mix", t: "Fertile, moisture-retentive mix with drainage." },
      { h: "Seedlings", t: "Harden off; plant at correct spacing for good air circulation." },
      { h: "Vegetative growth", t: "Blanch white types by tying leaves or pulling them over curd if sun is strong." },
      { h: "Organic & kitchen fertilizer", t: "Compost at planting; light compost tea during leaf growth. Avoid erratic drought—curds button or rice in stress." },
      { h: "Curd development", t: "Watch size and tightness; harvest before curd loosens and separates." },
      { h: "Harvest", t: "Cut head with some stem; use soon for best flavor." },
    ],
  },
  {
    id: "brussels-sprout",
    name: "Brussels sprouts",
    image: "https://images.unsplash.com/photo-1633348824836-a6142f5fb5aa?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Long season: start indoors early spring for fall/winter harvest in cool climates." },
      { h: "Germination", t: "Moderate temps; transplant when sturdy." },
      { h: "Potting mix", t: "Nutrient-rich compost-based mix for tall plants." },
      { h: "Seedlings", t: "Stake tall varieties in wind; lower leaves can be removed gradually to help sprouts size up (moderation)." },
      { h: "Vegetative growth", t: "Steady nitrogen early; reduce slightly as sprouts fill. Deep roots—mulch." },
      { h: "Organic & kitchen fertilizer", t: "Compost side-dress; nettle tea diluted during stalk growth. Late season: light banana peel tea for overall plant health." },
      { h: "Sprout fill", t: "Flavor improves after frost in many regions. Top-dress compost once mid-season if growth slows." },
      { h: "Harvest", t: "Twist or cut sprouts from bottom up when firm and 2–3 cm." },
    ],
  },
  {
    id: "carrot",
    name: "Carrot",
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Direct-sow early spring through summer for succession; fall crop in mild winters." },
      { h: "Germination", t: "Slow emergence; keep seedbed moist 2–3 weeks. Sow shallow; consider board cover until sprouts to hold moisture." },
      { h: "Potting mix", t: "Deep loose soil or deep container mix—no stones or heavy clay for straight roots." },
      { h: "Seedlings", t: "Thin ruthlessly to spacing on packet; thinnings can be baby carrots." },
      { h: "Vegetative growth", t: "Avoid high nitrogen that forks roots; steady even moisture prevents cracking." },
      { h: "Organic & kitchen fertilizer", t: "Light compost worked in before sowing is ideal. Mid-season: thin compost side-dress, not high-nitrogen liquids. Avoid fresh manure." },
      { h: "Root sizing", t: "Days to maturity on packet; shoulders may show at soil line when nearing size." },
      { h: "Harvest", t: "Loosen soil with fork; pull gently. Mulch for overwintering in mild zones." },
    ],
  },
  {
    id: "radish",
    name: "Radish",
    image: "https://images.unsplash.com/photo-1615485925693-2193e4b7a8d0?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "One of the earliest spring crops; quick succession every 10–14 days. Avoid peak heat for mild flavor." },
      { h: "Germination", t: "Fast in cool–warm soil; keep surface moist." },
      { h: "Potting mix", t: "Loose, stone-free; works in containers 15 cm+ deep." },
      { h: "Seedlings", t: "Thin early for round roots." },
      { h: "Vegetative growth", t: "Even moisture; too dry = woody, too lush N = all leaf." },
      { h: "Organic & kitchen fertilizer", t: "Little needed—compost at planting enough. Skip strong teas." },
      { h: "Bulb fill", t: "Check size by brushing soil from shoulder; harvest before splitting or bolting." },
      { h: "Harvest", t: "Pull when mature—late radishes turn pithy." },
    ],
  },
  {
    id: "beetroot",
    name: "Beetroot (beet)",
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Direct-sow 2–4 weeks before last frost; succession through summer where summers aren’t extreme." },
      { h: "Germination", t: "Soak seed clusters overnight optionally; each “seed” is multi-germ—thin to one seedling." },
      { h: "Potting mix", t: "Neutral pH, loose soil; boron deficiency causes internal breakdown—compost diversity helps." },
      { h: "Seedlings", t: "Thin to 8–10 cm; eat baby greens." },
      { h: "Vegetative growth", t: "Steady moisture for even roots; mulch." },
      { h: "Organic & kitchen fertilizer", t: "Compost side-dress; very dilute compost tea if leaves yellow. Banana peel tea extremely dilute late can support root crops alongside balanced compost." },
      { h: "Root swell", t: "Harvest from golf-ball size to full—larger can get woody." },
      { h: "Harvest", t: "Loosen soil; pull or dig. Greens are edible too." },
    ],
  },
  {
    id: "onion",
    name: "Onion",
    image: "https://images.unsplash.com/photo-1518977676601-b53f689f0018?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Sets, transplants, or seeds—seeds need very early indoor start (10–12 weeks) for bulbs in short seasons." },
      { h: "Germination", t: "Moderate temps; keep seedlings trimmed to 12 cm if leggy before transplant (optional trick)." },
      { h: "Potting mix", t: "Fertile, well-drained; onions are heavy feeders over long season." },
      { h: "Seedlings", t: "Transplant when pencil-thick for best bulb size (variety dependent)." },
      { h: "Vegetative growth", t: "Weed competition hurts yields badly. Consistent moisture until necks begin to soften." },
      { h: "Organic & kitchen fertilizer", t: "Compost at planting; mid-season compost side-dress or weak compost tea. Bulbing triggered by day length—match variety (long-day / short-day) to your latitude." },
      { h: "Bulbing & cure", t: "Tops fall when mature; cure dry, airy, shaded place 2–3 weeks." },
      { h: "Harvest", t: "Pull or lift gently; store only fully cured bulbs." },
    ],
  },
  {
    id: "garlic",
    name: "Garlic",
    image: "https://images.unsplash.com/photo-1546842931-886c4389f720?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Fall-planted in many regions (6–8 weeks before ground freezes); spring garlic where winters are harsh." },
      { h: "Germination / establishment", t: "Cloves root before winter; mulch heavily in cold zones." },
      { h: "Potting mix", t: "Deep fertile beds with compost; excellent drainage—garlic rots in wet winter soil." },
      { h: "Seedlings", t: "Not from seed for home growers—use disease-free cloves pointy-end up." },
      { h: "Vegetative growth", t: "Remove scapes from hardneck types for larger bulbs (scapes edible)." },
      { h: "Organic & kitchen fertilizer", t: "Compost in fall at planting; spring side-dress compost when growth resumes. Avoid excess fresh manure." },
      { h: "Bulb finish", t: "Lower leaves brown from bottom up—stop watering when ~½ leaves are brown." },
      { h: "Harvest", t: "Dig, don’t pull; cure like onions 3–4 weeks out of direct sun." },
    ],
  },
  {
    id: "potato",
    name: "Potato",
    image: "https://images.unsplash.com/photo-1585996743882-b8626f3ef28f?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Plant seed potatoes after frost danger when soil workable; “chit” indoors in light for strong sprouts." },
      { h: "Germination", t: "Tubers not true seeds—cut pieces with 2 eyes each; cure cut surface 24–48 h." },
      { h: "Potting mix", t: "Field: hilled rows with compost. Containers: very large pots; layer soil as plants grow." },
      { h: "Seedlings", t: "Hill soil or mulch when plants are 20 cm to exclude light from forming tubers." },
      { h: "Vegetative growth", t: "Even moisture during tuber set; drought then heavy water causes hollow heart." },
      { h: "Organic & kitchen fertilizer", t: "Compost at planting; avoid fresh manure (scab risk). Mid-season: compost side-dress at hilling. Light compost tea if vines pale—don’t overfeed nitrogen (all vine, few tubers)." },
      { h: "Tuber bulking", t: "Flowering not required for harvest; watch for pest/disease on leaves." },
      { h: "Harvest", t: "New potatoes: after flowering. Storage: wait until vines die back; cure dark/cool before storage." },
    ],
  },
  {
    id: "green-bean",
    name: "Green bean (bush / pole)",
    image: "https://images.unsplash.com/photo-1599623560578-253c6c50e4d1?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Direct-sow after frost when soil is warm; succession every 2–3 weeks. Pole beans need trellis." },
      { h: "Germination", t: "Warm soil; inoculant for beans (rhizobia) boosts nitrogen fixation—buy organic-rated." },
      { h: "Potting mix", t: "Not usually transplanted—sow in garden or large containers with support." },
      { h: "Seedlings", t: "Thin if crowded; protect from snails early." },
      { h: "Vegetative growth", t: "Pick constantly to keep plants productive; adequate water during pod fill." },
      { h: "Organic & kitchen fertilizer", t: "Light compost at planting is enough—beans fix N. If soil is poor: compost tea once early, not heavy nitrogen later." },
      { h: "Flowering & pods", t: "Pods form quickly after bloom; harvest young for tenderness." },
      { h: "Harvest", t: "Snap or filet types: pick before seeds swell inside. Shell beans left longer." },
    ],
  },
  {
    id: "pea",
    name: "Pea",
    image: "https://images.unsplash.com/photo-1592419040535-f739cba9b37e?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Very early spring as soon as soil can be worked; fall peas possible in cool climates." },
      { h: "Germination", t: "Cool soil OK; pre-soak 12 h optional to speed up." },
      { h: "Potting mix", t: "Rich, well-drained; provide trellis for tall types." },
      { h: "Seedlings", t: "Protect from birds; mulch keeps roots cool." },
      { h: "Vegetative growth", t: "Cool weather crop—declines in heat. Water during bloom and pod fill." },
      { h: "Organic & kitchen fertilizer", t: "Compost at sowing; inoculant helps. Avoid high nitrogen—peas fix their own." },
      { h: "Flowering & pods", t: "Pick snap peas flat; shell peas when plump." },
      { h: "Harvest", t: "Daily picking extends season; blanch and freeze extras." },
    ],
  },
  {
    id: "zucchini",
    name: "Zucchini (courgette)",
    image: "https://images.unsplash.com/photo-1591951428414-868c56910ac9?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "After frost; 2–3 plants often enough for a family—very productive." },
      { h: "Germination", t: "Warm soil; direct-sow or start indoors 2–3 weeks (don’t start too early)." },
      { h: "Potting mix", t: "Rich compost soil; large containers (40 L+) for one plant." },
      { h: "Seedlings", t: "Transplant carefully; protect from cucumber beetle." },
      { h: "Vegetative growth", t: "Huge leaves—mulch soil; consistent water prevents misshapen fruit." },
      { h: "Organic & kitchen fertilizer", t: "Compost at planting; mid-season side-dress compost. Flowering/fruit: diluted banana peel tea + compost tea rotation. Pick small fruits to keep plant productive." },
      { h: "Flowering & fruit", t: "Both male/female flowers; hand-pollinate if fruits abort." },
      { h: "Harvest", t: "Pick at 15–20 cm for best texture; monsters are still edible stuffed." },
    ],
  },
  {
    id: "eggplant",
    name: "Eggplant (aubergine)",
    image: "https://images.unsplash.com/photo-1628773820237-5515e2d8331c?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Start indoors 8–10 weeks before heat; needs long warm season." },
      { h: "Germination", t: "Warmth 24–30°C; can be slow and spotty." },
      { h: "Potting mix", t: "Rich mix; large final containers or garden beds with compost." },
      { h: "Seedlings", t: "Pot up before root-bound; stake heavy-fruited types." },
      { h: "Vegetative growth", t: "Full sun, heat, even water. Mulch reduces blossom drop in some cases." },
      { h: "Organic & kitchen fertilizer", t: "Compost + castings at transplant. Growth: compost tea. Fruiting: potassium from banana peel tea (dilute); comfrey tea. Avoid cold water on roots." },
      { h: "Flowering & fruit", t: "Fruits need support; harvest glossy skin before seeds harden." },
      { h: "Harvest", t: "Cut with pruners; regular picking increases yield." },
    ],
  },
  {
    id: "cabbage",
    name: "Cabbage",
    image: "https://images.unsplash.com/photo-1594282486552-05b4d6f7a457?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Spring and fall crops; transplants common for head timing." },
      { h: "Germination", t: "Moderate temps; thin/transplant for big heads." },
      { h: "Potting mix", t: "Steady moisture retention + drainage; heavy feeder." },
      { h: "Seedlings", t: "Harden off; space for final head diameter." },
      { h: "Vegetative growth", t: "Watch for caterpillars—row cover or organic Bt. Consistent water prevents split heads." },
      { h: "Organic & kitchen fertilizer", t: "Compost at plant; mid-growth compost side-dress or weak nettle tea. Heading: avoid huge nitrogen late—can split heads." },
      { h: "Head formation", t: "Firm when squeezed lightly; harvest before heads crack from rain after dry spell." },
      { h: "Harvest", t: "Cut stem; remove outer wrapper leaves if damaged." },
    ],
  },
  {
    id: "pumpkin",
    name: "Pumpkin & winter squash",
    image: "https://images.unsplash.com/photo-1506917728687-e429927958c9?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "After frost; need long warm season—check days to maturity." },
      { h: "Germination", t: "Warm soil; plant 3–4 seeds per hill; thin to 2 best vines." },
      { h: "Potting mix", t: "Very fertile ground or huge containers; vines sprawl meters." },
      { h: "Seedlings", t: "Handle squash roots gently if transplanting." },
      { h: "Vegetative growth", t: "Redirect vines if needed; mulch fruit off soil to prevent rot." },
      { h: "Organic & kitchen fertilizer", t: "Compost trenches at planting. Vine run: compost tea monthly. Fruit set: banana peel tea diluted; keep phosphorus sources organic (bone meal in soil at start)." },
      { h: "Flowering & fruit", t: "Hand-pollinate if few bees; limit fruit number on small vines for size." },
      { h: "Harvest", t: "Stem corky and skin hard; cure 10–14 days in warm dry place before storage." },
    ],
  },
  {
    id: "sweet-corn",
    name: "Sweet corn",
    image: "https://images.unsplash.com/photo-1500937386661-e3ac335e8cee?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Warm soil 18°C+; plant in blocks for wind pollination (min ~4×4 plants)." },
      { h: "Germination", t: "Direct-sow 3–5 cm deep; protect from birds." },
      { h: "Potting mix", t: "Deep fertile soil with high nitrogen demand—compost-heavy." },
      { h: "Seedlings", t: "Thin to spacing on packet; side-dress schedule matters." },
      { h: "Vegetative growth", t: "Heavy water at tasseling; mulch reduces evaporation." },
      { h: "Organic & kitchen fertilizer", t: "Compost at sowing; when knee-high, side-dress compost again. Nettle tea (dilute) supplies nitrogen if leaves pale. At silk: ensure even moisture—potsassium from very dilute banana tea optional." },
      { h: "Pollination & kernels", t: "Silks emerge—each silk = one kernel; pollen from tassel must land within ~48 h of silk emergence for that row." },
      { h: "Harvest", t: "Milky sap when kernel punctured; cook soon after picking for sweetness." },
    ],
  },
  {
    id: "okra",
    name: "Okra",
    image: "https://images.unsplash.com/photo-1596798437812-c340b2c89170?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Hot climates after soil warms; soak seed 12 h in warm water to soften coat." },
      { h: "Germination", t: "Needs heat; can be slow." },
      { h: "Potting mix", t: "Well-drained fertile mix; large pots in cool areas to move to sun." },
      { h: "Seedlings", t: "Don’t disturb taproot—direct-sow preferred where season is long enough." },
      { h: "Vegetative growth", t: "Harvest every 1–2 days when pods finger-sized or they turn woody." },
      { h: "Organic & kitchen fertilizer", t: "Compost at plant; during heavy pick: compost tea between harvests. Likes steady heat and moisture." },
      { h: "Flowering & pods", t: "Beautiful flowers; pods follow quickly in heat." },
      { h: "Harvest", t: "Wear gloves on spiny types; cut with shears." },
    ],
  },
  {
    id: "swiss-chard",
    name: "Swiss chard",
    image: "https://images.unsplash.com/photo-1506806732259-39c2d3a80c01?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Spring through fall; tolerates more heat than spinach." },
      { h: "Germination", t: "Multi-germ seed—thin to one; or start in cells." },
      { h: "Potting mix", t: "Rich moisture-retentive soil; great in containers." },
      { h: "Seedlings", t: "Space for large leaves; consistent water." },
      { h: "Vegetative growth", t: "Cut outer leaves; plant keeps producing." },
      { h: "Organic & kitchen fertilizer", t: "Compost at plant; mid-season side-dress or dilute compost tea if growth slows." },
      { h: "Bolting", t: "Biennial grown as annual; replace if flower stalk forms and flavor shifts." },
      { h: "Harvest", t: "Tender leaves and stems; cook stems longer than greens." },
    ],
  },
  {
    id: "celery",
    name: "Celery",
    image: "https://images.unsplash.com/photo-1589538793562-dffd59eeb7d?auto=format&fit=crop&w=600&q=80",
    sections: [
      { h: "When to plant", t: "Start indoors 10–12 weeks before transplant—long, cool season." },
      { h: "Germination", t: "Light may help; surface sow; keep moist 2–3 weeks." },
      { h: "Potting mix", t: "Constant moisture, rich organic mix; celery is a heavy drinker." },
      { h: "Seedlings", t: "Harden off; plant deeply if trenching for blanching (optional)." },
      { h: "Vegetative growth", t: "Never let dry out—stringy stalks result. Mulch." },
      { h: "Organic & kitchen fertilizer", t: "Compost + worm castings; frequent weak compost tea. Avoid gaps in watering more than chasing synthetic boosters." },
      { h: "Stalk fill", t: "Blanch by wrapping or boxes if you want pale stalks." },
      { h: "Harvest", t: "Cut whole plant or outer stalks as needed." },
    ],
  },
];
